# Generated by Django 4.1 on 2022-10-18 07:58

import datetime
import device.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="deviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(null=True, unique=True)),
                ("port", models.IntegerField(default=80)),
                ("user_id", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=10)),
                (
                    "master_status",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default="NO",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        default="Offline",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=25)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("none", "Non"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("User", "User"),
                            ("Visitor", "Visitor"),
                            ("Blocklist", "Blocklist"),
                        ],
                        default="User",
                        max_length=10,
                    ),
                ),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                ("room_number", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "end_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2037, 12, 31, 23, 59, 59, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to=device.models.upload_to),
                ),
                (
                    "IP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.devicedetails",
                    ),
                ),
            ],
        ),
    ]
